DROP TABLE USUARIOS CASCADE CONSTRAINTS PURGE;
DROP TABLE EQUIPO CASCADE CONSTRAINTS PURGE;

DROP TABLE JUGADOR CASCADE CONSTRAINTS PURGE;
DROP TABLE PARTIDO CASCADE CONSTRAINTS PURGE;
DROP TABLE JORNADA CASCADE CONSTRAINTS PURGE;

CREATE TABLE EQUIPO(
    ID_EQUIPO NUMBER(10)  GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_EQUIPO_PK PRIMARY KEY, 
    NOMBRE_EQUIPO VARCHAR(50) NOT NULL UNIQUE, 
    PRESUPUESTO NUMBER(9,2) CONSTRAINT PRESUPUESTO_CHK CHECK (PRESUPUESTO < 200000) NOT NULL, 
    PUNTUACION NUMBER(10) DEFAULT 0
);

CREATE TABLE JORNADA(
    ID_JORNADA NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_JORNADA_PK PRIMARY KEY, 
    FECHA DATE, 
    PUNTOSTOT NUMBER(10) DEFAULT 0 
);

CREATE TABLE USUARIOS(
    ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_USUARIO_PK PRIMARY KEY,
    ID_EQUIPO NUMBER(10) DEFAULT NULL,  
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    CONTRASEINA VARCHAR(50) NOT NULL, 
    ENUM_TIPOS VARCHAR(20) CONSTRAINT ENUM_TIPOS_CHK CHECK (ENUM_TIPOS IN ('DUEÑOS', 'ADMINISTRADOR', 'USUARIO')),
    CONSTRAINT FK_ID_EQUIPO0 FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE JUGADOR(
    ID_JUGADOR NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_JUGADOR_PK PRIMARY KEY, 
    SALARIO NUMBER(9,2) NOT NULL, -- Asegurando que haya suficiente espacio para números mayores
    NOMBRE VARCHAR(50) NOT NULL, 
    APELLIDO VARCHAR(50) NOT NULL, 
    NICKNAME VARCHAR(50) NOT NULL UNIQUE,
    ID_EQUIPO NUMBER(10),
    CONSTRAINT FK_ID_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE PARTIDO(
    ID_PARTIDO NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_PARTIDO_PK PRIMARY KEY, 
    PUNTUACION NUMBER(2) DEFAULT 0,
    FECHA DATE, 
    RESULTADO_EQUIPO1 NUMBER(5), 
    RESULTADO_EQUIPO2 NUMBER(5),
    ID_JORNADA NUMBER(10),
    ID_EQUIPO1 NUMBER(10), 
    ID_EQUIPO2 NUMBER(10),
    CONSTRAINT FK_ID_JORNADA FOREIGN KEY (ID_JORNADA) REFERENCES JORNADA(ID_JORNADA),
    CONSTRAINT FK_ID_EQUIPO1 FOREIGN KEY (ID_EQUIPO1) REFERENCES EQUIPO(ID_EQUIPO),
    CONSTRAINT FK_ID_EQUIPO2 FOREIGN KEY (ID_EQUIPO2) REFERENCES EQUIPO(ID_EQUIPO)
);


INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 1',50000, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 2',60000.12, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 3',33333.33, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 4',120000, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 5',55555, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 6',66600, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 7',100000.01, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 8',99999.99, 0);


-- Insertar jornadas
INSERT INTO JORNADA (FECHA, PUNTOSTOT) VALUES (TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10);
INSERT INTO JORNADA (FECHA, PUNTOSTOT) VALUES (TO_DATE('2024-05-02', 'YYYY-MM-DD'), 15);
INSERT INTO JORNADA (FECHA, PUNTOSTOT) VALUES (TO_DATE('2024-05-03', 'YYYY-MM-DD'), 20);


-- Insertar usuarios
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ADMIN', 'ADMIN','ADMIN', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('JON SAGAR', 'CRESPO', 'SAGAR', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('MISHA', 'CALVO', 'SOYCALVO', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ALBERTO', 'ORTIZ', 'ORTIZ', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ARNAU', 'GABRIEL', 'GABRIEL', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('IÑAKI', 'PEÑA', '123', 'DUEÑOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('CRISTINA', 'PEDROCHE', '123', 'DUEÑOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('IBAI', 'LLANOS', '123', 'DUEÑOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('MR', 'BESTIA', '123', 'USUARIO');


-- Insertar jugadores
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (50000, 'Juan', 'Pérez', 'ElRayo', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (52000, 'Carlos', 'López', 'CL10', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (51000, 'Luis', 'Martínez', 'Lucho', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (49500, 'Miguel', 'Gómez', 'MGZ', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (53000, 'Andrés', 'Ramírez', 'Andy', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (50500, 'Pedro', 'Sánchez', 'Pedrito', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (47000, 'Jorge', 'Díaz', 'JD7', 2);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (48000, 'Fernando', 'Torres', 'Nando', 2);


-- Insertar partidos
INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES (3, TO_DATE('2024-05-10', 'YYYY-MM-DD'), 3, 1, 1, 1, 2);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES (2, TO_DATE('2024-05-11', 'YYYY-MM-DD'), 2, 2, 2, 3, 4);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES (5, TO_DATE('2024-05-12', 'YYYY-MM-DD'), 0, 3, 3, 5, 6);




select * from EQUIPO; 
SELECT * FROM JORNADA; 
SELECT * FROM JUGADOR ; 
SELECT * FROM USUARIOS; 
SELECT * FROM PARTIDO; 




