DROP TABLE USUARIOS CASCADE CONSTRAINTS PURGE;
DROP TABLE EQUIPO CASCADE CONSTRAINTS PURGE;

DROP TABLE JUGADOR CASCADE CONSTRAINTS PURGE;
DROP TABLE PARTIDO CASCADE CONSTRAINTS PURGE;
DROP TABLE JORNADA CASCADE CONSTRAINTS PURGE;


-- TENER EN CUENTA QUE NO QUEREMOS COSAS DUPLICADAS 

CREATE TABLE EQUIPO(
    ID_EQUIPO NUMBER(10)  GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_EQUIPO_PK PRIMARY KEY, 
    NOMBRE_EQUIPO VARCHAR(50) NOT NULL UNIQUE, 
    PRESUPUESTO NUMBER(9,2) CONSTRAINT PRESUPUESTO_CHK CHECK (PRESUPUESTO < 200000) NOT NULL, 
    PUNTUACION NUMBER(10) DEFAULT 0
);

CREATE TABLE JORNADA(
    ID_JORNADA NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_JORNADA_PK PRIMARY KEY, 
    FECHA DATE, 
    PUNTOSTOT NUMBER(10) DEFAULT 0 
);

CREATE TABLE USUARIOS(
    ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_USUARIO_PK PRIMARY KEY,
    ID_EQUIPO NUMBER(10) DEFAULT NULL,  
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    CONTRASEINA VARCHAR(50) NOT NULL, 
    ENUM_TIPOS VARCHAR(20) CONSTRAINT ENUM_TIPOS_CHK CHECK (ENUM_TIPOS IN ('DUENOS', 'ADMINISTRADOR', 'USUARIO')),
    CONSTRAINT FK_ID_EQUIPO0 FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE JUGADOR(
    ID_JUGADOR NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_JUGADOR_PK PRIMARY KEY, 
    SALARIO NUMBER(9,2) NOT NULL, -- Asegurando que haya suficiente espacio para n?meros mayores
    NOMBRE VARCHAR(50) NOT NULL, 
    APELLIDO VARCHAR(50) NOT NULL, 
    NICKNAME VARCHAR(50) NOT NULL UNIQUE,
    ID_EQUIPO NUMBER(10) DEFAULT NULL,
    CONSTRAINT FK_ID_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE PARTIDO(
    ID_PARTIDO NUMBER(10) GENERATED ALWAYS AS IDENTITY CONSTRAINT ID_PARTIDO_PK PRIMARY KEY, 
    PUNTUACION VARCHAR(50) DEFAULT 0,
    FECHA DATE, 
    RESULTADO_EQUIPO1 NUMBER(5), 
    RESULTADO_EQUIPO2 NUMBER(5),
    ID_JORNADA NUMBER(10),
    ID_EQUIPO1 NUMBER(10), 
    ID_EQUIPO2 NUMBER(10),
    CONSTRAINT FK_ID_JORNADA FOREIGN KEY (ID_JORNADA) REFERENCES JORNADA(ID_JORNADA),
    CONSTRAINT FK_ID_EQUIPO1 FOREIGN KEY (ID_EQUIPO1) REFERENCES EQUIPO(ID_EQUIPO),
    CONSTRAINT FK_ID_EQUIPO2 FOREIGN KEY (ID_EQUIPO2) REFERENCES EQUIPO(ID_EQUIPO)
);


INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 1',50000, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 2',60000.12, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 3',33333.33, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 4',120000, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 5',55555, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 6',66600, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 7',100000.01, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO,PRESUPUESTO, PUNTUACION) VALUES('EQUIPO 8',99999.99, 0);


-- Insertar jornadas
INSERT INTO JORNADA (FECHA)
VALUES (TO_DATE('2024-05-01', 'YYYY-MM-DD'));

INSERT INTO JORNADA (FECHA)
VALUES (TO_DATE('2024-05-02', 'YYYY-MM-DD'));

INSERT INTO JORNADA (FECHA)
VALUES (TO_DATE('2024-05-03', 'YYYY-MM-DD'));

INSERT INTO JORNADA (FECHA)
VALUES (TO_DATE('2024-05-07', 'YYYY-MM-DD'));

INSERT INTO JORNADA (FECHA)
VALUES (TO_DATE('2024-05-08', 'YYYY-MM-DD'));

INSERT INTO JORNADA (FECHA)
VALUES (TO_DATE('2024-05-09', 'YYYY-MM-DD'));



-- Insertar usuarios
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ADMIN', 'ADMIN','ADMIN', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('JON SAGAR', 'CRESPO', 'SAGAR', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('MISHA', 'CALVO', 'SOYCALVO', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ALBERTO', 'ORTIZ', 'ORTIZ', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ARNAU', 'GABRIEL', 'GABRIEL', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ISAKI', 'PENA', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('CRISTINA', 'PEDROCHE', '123', 'DUENOS');
INSERT INTO USUARIOS (ID_EQUIPO,NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES (1,'IBAI', 'LLANOS', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('MR', 'BESTIA', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Luis', 'Ramirez', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Mar�a', 'Torres', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Javier', 'Gomez', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Andrea', 'Fernandez', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('CHANGO', '123', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Fernando', 'Lopez', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Elena', 'Sanchez', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Ra�l', 'Martinez', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Sof�a', 'Gutierrez', '123', 'DUENOS');


-- Insertar jugadores

-- Equipo 1 (ID_EQUIPO = 1)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (40000, 'Juan', 'Perez', 'ElRayo', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (42000, 'Carlos', 'Lopez', 'CL10', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (41000, 'Roberto', 'Garcia', 'Rober', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (35000, 'Sergio', 'Navarro', 'SerNav', 1);

-- Equipo 2 (ID_EQUIPO = 2)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (41000, 'Luis', 'Martinez', 'Lucho', 2);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (39500, 'Miguel', 'Gomez', 'MGZ', 2);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (43000, 'Andres', 'Ramirez', 'Andy', 2);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (36000, 'Elena', 'Fernandez', 'ElenF', 2);

-- Equipo 3 (ID_EQUIPO = 3)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (35000, 'Pimienta', 'Lata', 'Laton', 3);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (36000, 'Sofia', 'Martinez', 'Sofi', 3);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (37000, 'Valeria', 'Rodriguez', 'Vale', 3);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (30000, 'Manuel', 'Gomez', 'ManuG', 3);

-- Equipo 4 (ID_EQUIPO = 4)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (38000, 'Diego', 'Hernandez', 'Dieguito', 4);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (39000, 'Mariana', 'Lopez', 'Mari', 4);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (40000, 'Esteban', 'Gonzalez', 'Esteb', 4);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (38000, 'Rosa', 'Garcia', 'RosG', 4);


-- Equipo 5 (ID_EQUIPO = 5)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (41000, 'Alberto', 'Ruiz', 'Alby', 5);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (42000, 'Laura', 'Fernandez', 'Lau', 5);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (43000, 'Gabriel', 'Mendez', 'Gabi', 5);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (32000, 'David', 'Martinez', 'DavM', 5);

-- Equipo 6 (ID_EQUIPO = 6)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (44000, 'Samuel', 'Diaz', 'Sam', 6);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (45000, 'Claudia', 'Sanchez', 'Clau', 6);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (46000, 'Victor', 'Castro', 'Vic', 6);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (25000, 'Paula', 'Lopez', 'PauL', 6);


-- Equipo 7 (ID_EQUIPO = 7)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (47000, 'Patricia', 'Molina', 'Paty', 7);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (48000, 'Eduardo', 'Morales', 'Eddie', 7);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (49000, 'Isabel', 'Ramirez', 'Isa', 7);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (17000, 'Hugo', 'Ramirez', 'HugR', 7);

-- Equipo 8 (ID_EQUIPO = 8)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (40000, 'Fernando', 'Perez', 'Fer', 8);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (41000, 'Silvia', 'Gutierrez', 'Sil', 8);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (42000, 'Andreu', 'Lopez', 'Andru', 8);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (16000, 'Clara', 'Sanchez', 'ClaS', 8);

-- Jugadores sin equipo 
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (17000, 'Sagar', 'crespo', 'sacre');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (40000, 'misha', 'zugazua', 'misha_zl');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (15000, 'alberto', 'pokem', 'cartitas');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (1000, 'Arnau', 'pobre', 'JaJapobre');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (18000, 'Daniel', 'Suarez', 'DaniS');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (22000, 'Lucia', 'Morales', 'LuMor');

-- Insertar partidos
INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('3', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 3, 1, 1, 1, 2);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('2', TO_DATE('2024-05-02', 'YYYY-MM-DD'), 2, 2, 2, 3, 4);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('5', TO_DATE('2024-05-03', 'YYYY-MM-DD'), 0, 3, 3, 5, 6);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('4', TO_DATE('2024-05-07', 'YYYY-MM-DD'), 2, 1, 4, 7, 8);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('3', TO_DATE('2024-05-08', 'YYYY-MM-DD'), 1, 1, 5, 2, 5);

COMMIT; 


CREATE OR REPLACE TRIGGER MAX_JUGADORES
FOR INSERT OR UPDATE ON JUGADOR
COMPOUND TRIGGER

    TYPE t_cod_equipos IS TABLE OF JUGADOR.ID_EQUIPO%TYPE INDEX BY PLS_INTEGER;
    cod_equipos t_cod_equipos;
    idx INTEGER := 0;

    PROCEDURE agregar_equipo(p_id_equipo JUGADOR.ID_EQUIPO%TYPE) IS
    BEGIN
        
        IF p_id_equipo IS NOT NULL THEN
            FOR i IN 1 .. idx LOOP
                IF cod_equipos(i) = p_id_equipo THEN
                    RETURN; 
                END IF;
            END LOOP;
            idx := idx + 1;
            cod_equipos(idx) := p_id_equipo;
        END IF;
    END;

BEFORE EACH ROW IS
BEGIN
    agregar_equipo(:NEW.ID_EQUIPO);
END BEFORE EACH ROW;

AFTER STATEMENT IS
    v_num_jugadores NUMBER;
BEGIN
    FOR i IN 1 .. idx LOOP
        SELECT COUNT(*) INTO v_num_jugadores
        FROM JUGADOR
        WHERE ID_EQUIPO = cod_equipos(i);

        IF v_num_jugadores > 6 THEN
            RAISE_APPLICATION_ERROR(-20001, 'El equipo con ID ' || cod_equipos(i) || ' ya tiene más de 6 jugadores.');
        END IF;
    END LOOP;
END AFTER STATEMENT;

END MAX_JUGADORES;
/

CREATE OR REPLACE TRIGGER JUGADORES_MINIMOS
BEFORE INSERT OR UPDATE ON EQUIPO
FOR EACH ROW
DECLARE
  JUGADORES_TOTALES NUMBER(10);
BEGIN
  SELECT COUNT(*) INTO JUGADORES_TOTALES
  FROM JUGADOR
  WHERE ID_EQUIPO = :NEW.ID_EQUIPO;
  IF JUGADORES_TOTALES < 2 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Equipo con menos de 2 jugadores');
  END IF;
END;


CREATE OR REPLACE TRIGGER SALARIO_MAX_JUGADOR
FOR INSERT OR UPDATE ON JUGADOR
COMPOUND TRIGGER
    SALARIO_TOTAL NUMBER := 0; 
    V_NUEVO_COD_EQUIPO NUMBER(12); 
BEFORE EACH ROW IS
    BEGIN
        V_NUEVO_COD_EQUIPO := :NEW.ID_EQUIPO;
    END BEFORE EACH ROW;
    
AFTER STATEMENT IS
    BEGIN
        SELECT NVL(SUM(SALARIO), 0) INTO SALARIO_TOTAL
        FROM JUGADOR
        WHERE ID_EQUIPO = V_NUEVO_COD_EQUIPO;
        IF SALARIO_TOTAL > 200000 THEN
            RAISE_APPLICATION_ERROR(-20004,'LIMITE SALARIO ALCANZADO');
        END IF;
    END AFTER STATEMENT;
END;


select * from EQUIPO; 
SELECT * FROM JORNADA; 
SELECT * FROM JUGADOR ; 
SELECT * FROM USUARIOS; 
SELECT * FROM PARTIDO; 

SELECT J.ID_JORNADA, J.FECHA, E1.NOMBRE_EQUIPO AS Equipo1, E2.NOMBRE_EQUIPO AS Equipo2, E1.PUNTUACION || ' - ' || E2.PUNTUACION AS PUNTUACION , P.RESULTADO_EQUIPO1, P.RESULTADO_EQUIPO2 
FROM JORNADA J 
INNER JOIN PARTIDO P ON J.ID_JORNADA = P.ID_JORNADA 
INNER JOIN EQUIPO E1 ON P.ID_EQUIPO1 = E1.ID_EQUIPO 
INNER JOIN EQUIPO E2 ON P.ID_EQUIPO2 = E2.ID_EQUIPO;



