DROP TABLE IF EXISTS PARTIDO;
DROP TABLE IF EXISTS JUGADOR;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS JORNADA;
DROP TABLE IF EXISTS EQUIPO;

CREATE TABLE EQUIPO (
    ID_EQUIPO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_EQUIPO VARCHAR(50) NOT NULL UNIQUE,
    PRESUPUESTO DECIMAL(9,2) NOT NULL,
    PUNTUACION INT DEFAULT 0,
    CHECK (PRESUPUESTO < 200000)
);

CREATE TABLE JORNADA (
    ID_JORNADA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE,
    PUNTOSTOT INT DEFAULT 0
);

CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_EQUIPO INT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    CONTRASEINA VARCHAR(50) NOT NULL,
    ENUM_TIPOS ENUM('DUENOS', 'ADMINISTRADOR', 'USUARIO'),
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE JUGADOR (
    ID_JUGADOR INT AUTO_INCREMENT PRIMARY KEY,
    SALARIO DECIMAL(9,2) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    NICKNAME VARCHAR(50) NOT NULL UNIQUE,
    ID_EQUIPO INT,
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE PARTIDO (
    ID_PARTIDO INT AUTO_INCREMENT PRIMARY KEY,
    PUNTUACION VARCHAR(50) DEFAULT '0',
    FECHA DATE,
    RESULTADO_EQUIPO1 INT,
    RESULTADO_EQUIPO2 INT,
    ID_JORNADA INT,
    ID_EQUIPO1 INT,
    ID_EQUIPO2 INT,
    FOREIGN KEY (ID_JORNADA) REFERENCES JORNADA(ID_JORNADA),
    FOREIGN KEY (ID_EQUIPO1) REFERENCES EQUIPO(ID_EQUIPO),
    FOREIGN KEY (ID_EQUIPO2) REFERENCES EQUIPO(ID_EQUIPO)
);


-- Insertar equipos
INSERT INTO EQUIPO (NOMBRE_EQUIPO, PRESUPUESTO, PUNTUACION) VALUES ('EQUIPO 1', 50000, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO, PRESUPUESTO, PUNTUACION) VALUES ('EQUIPO 2', 60000.12, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO, PRESUPUESTO, PUNTUACION) VALUES ('EQUIPO 3', 33333.33, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO, PRESUPUESTO, PUNTUACION) VALUES ('EQUIPO 4', 120000, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO, PRESUPUESTO, PUNTUACION) VALUES ('EQUIPO 5', 55555, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO, PRESUPUESTO, PUNTUACION) VALUES ('EQUIPO 6', 66600, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO, PRESUPUESTO, PUNTUACION) VALUES ('EQUIPO 7', 100000.01, 0);
INSERT INTO EQUIPO (NOMBRE_EQUIPO, PRESUPUESTO, PUNTUACION) VALUES ('EQUIPO 8', 99999.99, 0);

-- Insertar jornadas
INSERT INTO JORNADA (FECHA) VALUES ('2024-05-01');
INSERT INTO JORNADA (FECHA) VALUES ('2024-05-02');
INSERT INTO JORNADA (FECHA) VALUES ('2024-05-03');
INSERT INTO JORNADA (FECHA) VALUES ('2024-05-07');
INSERT INTO JORNADA (FECHA) VALUES ('2024-05-08');
INSERT INTO JORNADA (FECHA) VALUES ('2024-05-09');

-- Insertar usuarios
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ADMIN', 'ADMIN', 'ADMIN', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('JON SAGAR', 'CRESPO', 'SAGAR', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('MISHA', 'CALVO', 'SOYCALVO', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ALBERTO', 'ORTIZ', 'ORTIZ', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ARNAU', 'GABRIEL', 'GABRIEL', 'ADMINISTRADOR');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('ISAKI', 'PENA', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('CRISTINA', 'PEDROCHE', '123', 'DUENOS');
INSERT INTO USUARIOS (ID_EQUIPO, NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES (1, 'IBAI', 'LLANOS', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('MR', 'BESTIA', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Luis', 'Ramirez', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('María', 'Torres', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Javier', 'Gomez', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Andrea', 'Fernandez', '123', 'USUARIO');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('CHANGO', '123', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Fernando', 'Lopez', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Elena', 'Sanchez', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Raúl', 'Martinez', '123', 'DUENOS');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CONTRASEINA, ENUM_TIPOS) VALUES ('Sofía', 'Gutierrez', '123', 'DUENOS');

-- Insertar jugadores

-- Equipo 1 (ID_EQUIPO = 1)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (40000, 'Juan', 'Perez', 'ElRayo', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (42000, 'Carlos', 'Lopez', 'CL10', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (41000, 'Roberto', 'Garcia', 'Rober', 1);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (35000, 'Sergio', 'Navarro', 'SerNav', 1);

-- Equipo 2 (ID_EQUIPO = 2)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (41000, 'Luis', 'Martinez', 'Lucho', 2);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (39500, 'Miguel', 'Gomez', 'MGZ', 2);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (43000, 'Andres', 'Ramirez', 'Andy', 2);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (36000, 'Elena', 'Fernandez', 'ElenF', 2);

-- Equipo 3 (ID_EQUIPO = 3)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (35000, 'Pimienta', 'Lata', 'Laton', 3);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (36000, 'Sofia', 'Martinez', 'Sofi', 3);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (37000, 'Valeria', 'Rodriguez', 'Vale', 3);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (30000, 'Manuel', 'Gomez', 'ManuG', 3);

-- Equipo 4 (ID_EQUIPO = 4)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (38000, 'Diego', 'Hernandez', 'Dieguito', 4);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (39000, 'Mariana', 'Lopez', 'Mari', 4);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (40000, 'Esteban', 'Gonzalez', 'Esteb', 4);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (38000, 'Rosa', 'Garcia', 'RosG', 4);

-- Equipo 5 (ID_EQUIPO = 5)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (41000, 'Alberto', 'Ruiz', 'Alby', 5);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (42000, 'Laura', 'Fernandez', 'Lau', 5);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (43000, 'Gabriel', 'Mendez', 'Gabi', 5);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (32000, 'David', 'Martinez', 'DavM', 5);

-- Equipo 6 (ID_EQUIPO = 6)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (44000, 'Samuel', 'Diaz', 'Sam', 6);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (45000, 'Claudia', 'Sanchez', 'Clau', 6);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (46000, 'Victor', 'Castro', 'Vic', 6);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (25000, 'Paula', 'Lopez', 'PauL', 6);

-- Equipo 7 (ID_EQUIPO = 7)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (47000, 'Patricia', 'Molina', 'Paty', 7);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (48000, 'Eduardo', 'Morales', 'Eddie', 7);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (49000, 'Isabel', 'Ramirez', 'Isa', 7);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (17000, 'Hugo', 'Ramirez', 'HugR', 7);

-- Equipo 8 (ID_EQUIPO = 8)
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (40000, 'Fernando', 'Perez', 'Fer', 8);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (41000, 'Silvia', 'Gutierrez', 'Sil', 8);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (42000, 'Andreu', 'Lopez', 'Andru', 8);
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME, ID_EQUIPO) VALUES (16000, 'Clara', 'Sanchez', 'ClaS', 8);

-- Jugadores sin equipo
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (17000, 'Sagar', 'crespo', 'sacre');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (40000, 'misha', 'zugazua', 'misha_zl');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (15000, 'alberto', 'pokem', 'cartitas');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (1000, 'Arnau', 'pobre', 'JaJapobre');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (18000, 'Daniel', 'Suarez', 'DaniS');
INSERT INTO JUGADOR (SALARIO, NOMBRE, APELLIDO, NICKNAME) VALUES (22000, 'Lucia', 'Morales', 'LuMor');

-- Insertar partidos
INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('3', '2024-05-01', 3, 1, 1, 1, 2);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('2', '2024-05-02', 2, 2, 2, 3, 4);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('5', '2024-05-03', 0, 3, 3, 5, 6);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('4', '2024-05-07', 2, 1, 4, 7, 8);

INSERT INTO PARTIDO (PUNTUACION, FECHA, RESULTADO_EQUIPO1, RESULTADO_EQUIPO2, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
VALUES ('3', '2024-05-08', 1, 1, 5, 2, 5);

COMMIT;


CREATE OR REPLACE TRIGGER JUGADORES_MINIMOS
BEFORE UPDATE OR INSERT ON EQUIPO
FOR EACH ROW
DECLARE
  JUGADORES_TOTALES NUMBER;
BEGIN
  -- Verifica si el ID_EQUIPO ya existe (solo tiene sentido en UPDATE o insert manual)
  IF :NEW.ID_EQUIPO IS NOT NULL THEN
    SELECT COUNT(*) INTO JUGADORES_TOTALES
    FROM JUGADOR
    WHERE ID_EQUIPO = :NEW.ID_EQUIPO;

    IF JUGADORES_TOTALES < 4 THEN
      RAISE_APPLICATION_ERROR(-20002, 'El equipo debe tener al menos 4 jugadores.');
    END IF;
  END IF;
END;
/
